"""
BPE Tokenizer in the style of GPT-4: train with rustbpe, inference with tiktoken.

Also home to the cycled-RoPE position scheme (PositionTracker and friends), which lives
here because it is a property of how a conversation is *rendered* into tokens, and is
computed on CPU at tokenization time rather than inside the training loop.
"""

import os
import copy
from functools import lru_cache

SPECIAL_TOKENS = [
    # every document begins with the Beginning of Sequence (BOS) token that delimits documents
    "<|bos|>",
    # tokens below are only used during finetuning to render Conversations into token ids
    "<|user_start|>", # user messages
    "<|user_end|>",
    "<|assistant_start|>", # assistant messages
    "<|assistant_end|>",
    "<|python_start|>", # assistant invokes python REPL tool
    "<|python_end|>",
    "<|output_start|>", # python REPL outputs back to assistant
    "<|output_end|>",
]

# NOTE: this split pattern deviates from GPT-4 in that we use \p{N}{1,2} instead of \p{N}{1,3}
# I did this because I didn't want to "waste" too many tokens on numbers for smaller vocab sizes.
# I verified that 2 is the sweet spot for vocab size of 32K. 1 is a bit worse, 3 was worse still.
SPLIT_PATTERN = r"""'(?i:[sdmt]|ll|ve|re)|[^\r\n\p{L}\p{N}]?+\p{L}+|\p{N}{1,2}| ?[^\s\p{L}\p{N}]++[\r\n]*|\s*[\r\n]|\s+(?!\S)|\s+"""

# -----------------------------------------------------------------------------
# Cycled RoPE: message-strided virtual positions
#
# The idea: a message's positional encoding should not depend on how long the messages
# before it were. So at every message boundary we jump the virtual position to the next
# multiple of `message_stride`, with a parity that encodes *who is speaking*:
#
#   even multiples (2k * M)     <- fed to the model:      BOS, user turns, tool output
#   odd multiples ((2k+1) * M)  <- generated by the model: assistant turns, tool code
#
# Within a message, positions increment contiguously, so the base model's local position
# semantics are untouched; only the offsets between messages change.
#
#   BOS  user_start  "hi"  user_end  |  asst_start  "hello"  asst_end  |  user_start  "ok"
#   pos:  0    1       2      3      |     512        513       514    |     1024      1025
#         <---------- even (0*M) --->  <------- odd (1*M) ----------->  <-- even (2*M) -->
#
# Note BOS does not get a slot of its own: it is already in an even slot and the user turn
# that follows wants the same parity, so it simply continues contiguously.

USER_PARITY = 0      # even multiples of the stride
ASSISTANT_PARITY = 1 # odd multiples of the stride


def conversation_boundaries(tokenizer):
    """
    Build the two boundary maps used by PositionTracker for nanochat's chat format.

    align_at:    token id -> parity. This token *starts* a new segment, so it is the first
                 token placed at the newly aligned position.
    align_after: token id -> parity. The token *following* this one starts a new segment.
                 Used for <|output_end|>: the tool output owns its (even) slot right up to
                 its closing token, and whatever the assistant says next belongs to a fresh
                 odd slot.
    """
    special = tokenizer.encode_special
    align_at = {
        tokenizer.get_bos_token_id():   USER_PARITY,      # start of the document
        special("<|user_start|>"):      USER_PARITY,      # user turn
        special("<|output_start|>"):    USER_PARITY,      # python output, fed back to the model
        special("<|assistant_start|>"): ASSISTANT_PARITY, # assistant turn
        special("<|python_start|>"):    ASSISTANT_PARITY, # tool code, written by the assistant
    }
    align_after = {
        special("<|output_end|>"):      ASSISTANT_PARITY, # assistant resumes after tool output
    }
    return align_at, align_after


class PositionTracker:
    """
    Incremental cycled-RoPE position generator: feed it token ids one at a time (or in
    bulk) and it returns the virtual position of each. Incremental so that the same code
    drives both tokenization-time batching and token-by-token decoding in the Engine.

    With message_stride <= 0 this degenerates to plain contiguous positions, which keeps
    every caller free of "is the feature on?" branching.
    """

    def __init__(self, message_stride, align_at=None, align_after=None):
        self.message_stride = message_stride
        self.align_at = align_at or {}
        self.align_after = align_after or {}
        self.pos = 0            # position the next token will receive
        self.slot = 0           # index of the stride multiple the current segment started at
        self.pending = None     # parity requested by the previous token, applied to this one

    def clone(self):
        """Copy of the current state, e.g. to fan a prefilled prompt out to N decode rows."""
        other = PositionTracker(self.message_stride, self.align_at, self.align_after)
        other.pos, other.slot, other.pending = self.pos, self.slot, self.pending
        return other

    def _align(self, parity):
        """Move self.pos to the start of the next stride multiple with the given parity."""
        M = self.message_stride
        # Stay put if we are still inside the current segment's slot and it already has the
        # right parity. This is what lets BOS and the user turn that follows it share slot 0.
        if self.slot % 2 == parity and self.pos < (self.slot + 1) * M:
            return
        # Otherwise take the first slot with the right parity that lies at or after us. A
        # message that overflowed its slot therefore skips ahead rather than starting midway.
        m = -(-self.pos // M)  # ceil division: the first slot boundary at or after pos
        if m % 2 != parity:
            m += 1
        self.pos = m * M
        self.slot = m

    def step(self, token_id):
        """Return the virtual position of token_id and advance the state."""
        if self.message_stride > 0:
            parity = self.pending if self.pending is not None else self.align_at.get(token_id)
            self.pending = self.align_after.get(token_id)
            if parity is not None:
                self._align(parity)
        pos = self.pos
        self.pos += 1
        return pos

    def extend(self, token_ids):
        """Return the virtual positions of a whole run of tokens."""
        return [self.step(token_id) for token_id in token_ids]


def compute_conversation_position_ids(ids, message_stride, align_at=None, align_after=None):
    """
    Virtual positions for a rendered conversation, as a list of ints the same length as ids.

    ids:            list[int], a conversation rendered by render_conversation
    message_stride: int, 0 (or less) disables striding and yields contiguous positions
    align_at/after: boundary maps, see conversation_boundaries()
    """
    tracker = PositionTracker(message_stride, align_at, align_after)
    return tracker.extend(ids)


# -----------------------------------------------------------------------------
# Tokenizer based on rustbpe + tiktoken combo
import pickle
import rustbpe
import tiktoken

class RustBPETokenizer:
    """Light wrapper around tiktoken (for efficient inference) but train with rustbpe"""

    def __init__(self, enc, bos_token):
        self.enc = enc
        self.bos_token_id = self.encode_special(bos_token)

    @classmethod
    def train_from_iterator(cls, text_iterator, vocab_size):
        # 1) train using rustbpe
        tokenizer = rustbpe.Tokenizer()
        # the special tokens are inserted later in __init__, we don't train them here
        vocab_size_no_special = vocab_size - len(SPECIAL_TOKENS)
        assert vocab_size_no_special >= 256, f"vocab_size_no_special must be at least 256, got {vocab_size_no_special}"
        tokenizer.train_from_iterator(text_iterator, vocab_size_no_special, pattern=SPLIT_PATTERN)
        # 2) construct the associated tiktoken encoding for inference
        pattern = tokenizer.get_pattern()
        mergeable_ranks_list = tokenizer.get_mergeable_ranks()
        mergeable_ranks = {bytes(k): v for k, v in mergeable_ranks_list}
        tokens_offset = len(mergeable_ranks)
        special_tokens = {name: tokens_offset + i for i, name in enumerate(SPECIAL_TOKENS)}
        enc = tiktoken.Encoding(
            name="rustbpe",
            pat_str=pattern,
            mergeable_ranks=mergeable_ranks, # dict[bytes, int] (token bytes -> merge priority rank)
            special_tokens=special_tokens, # dict[str, int] (special token name -> token id)
        )
        return cls(enc, "<|bos|>")

    @classmethod
    def from_directory(cls, tokenizer_dir):
        pickle_path = os.path.join(tokenizer_dir, "tokenizer.pkl")
        with open(pickle_path, "rb") as f:
            enc = pickle.load(f)
        return cls(enc, "<|bos|>")

    @classmethod
    def from_pretrained(cls, tiktoken_name):
        # https://github.com/openai/tiktoken/blob/eedc8563/tiktoken_ext/openai_public.py
        enc = tiktoken.get_encoding(tiktoken_name)
        # tiktoken calls the special document delimiter token "<|endoftext|>"
        # yes this is confusing because this token is almost always PREPENDED to the beginning of the document
        # it most often is used to signal the start of a new sequence to the LLM during inference etc.
        # so in nanoChat we always use "<|bos|>" short for "beginning of sequence", but historically it is often called "<|endoftext|>".
        return cls(enc, "<|endoftext|>")

    def get_vocab_size(self):
        return self.enc.n_vocab

    def get_special_tokens(self):
        return self.enc.special_tokens_set

    def id_to_token(self, id):
        return self.enc.decode([id])

    @lru_cache(maxsize=32)
    def encode_special(self, text):
        return self.enc.encode_single_token(text)

    def get_bos_token_id(self):
        return self.bos_token_id

    def encode(self, text, prepend=None, append=None, num_threads=8):
        # text can be either a string or a list of strings

        if prepend is not None:
            prepend_id = prepend if isinstance(prepend, int) else self.encode_special(prepend)
        if append is not None:
            append_id = append if isinstance(append, int) else self.encode_special(append)

        if isinstance(text, str):
            ids = self.enc.encode_ordinary(text)
            if prepend is not None:
                ids.insert(0, prepend_id) # TODO: slightly inefficient here? :( hmm
            if append is not None:
                ids.append(append_id)
        elif isinstance(text, list):
            ids = self.enc.encode_ordinary_batch(text, num_threads=num_threads)
            if prepend is not None:
                for ids_row in ids:
                    ids_row.insert(0, prepend_id) # TODO: same
            if append is not None:
                for ids_row in ids:
                    ids_row.append(append_id)
        else:
            raise ValueError(f"Invalid input type: {type(text)}")

        return ids

    def __call__(self, *args, **kwargs):
        return self.encode(*args, **kwargs)

    def decode(self, ids):
        return self.enc.decode(ids)

    def decode_single_token_bytes(self, token_id):
        return self.enc.decode_single_token_bytes(token_id)

    def save(self, tokenizer_dir):
        # save the encoding object to disk
        os.makedirs(tokenizer_dir, exist_ok=True)
        pickle_path = os.path.join(tokenizer_dir, "tokenizer.pkl")
        with open(pickle_path, "wb") as f:
            pickle.dump(self.enc, f)
        print(f"Saved tokenizer encoding to {pickle_path}")

    @lru_cache(maxsize=1)
    def _conversation_boundaries(self):
        """Cached boundary maps for the cycled-RoPE position scheme (see module header)."""
        return conversation_boundaries(self)

    def render_conversation(self, conversation, max_tokens=2048, message_stride=0, return_positions=False):
        """
        Tokenize a single Chat conversation (which we call a "doc" or "document" here).
        Returns:
        - ids: list[int] is a list of token ids of this rendered conversation
        - mask: list[int] of same length, mask = 1 for tokens that the Assistant is expected to train on.
        - positions: list[int] of same length, only when return_positions=True. Virtual RoPE
          positions under the cycled-RoPE scheme; contiguous when message_stride is 0.
        """
        # ids, masks that we will return and a helper function to help build them up.
        ids, mask = [], []
        def add_tokens(token_ids, mask_val):
            if isinstance(token_ids, int):
                token_ids = [token_ids]
            ids.extend(token_ids)
            mask.extend([mask_val] * len(token_ids))

        # sometimes the first message is a system message...
        # => just merge it with the second (user) message
        if conversation["messages"][0]["role"] == "system":
            # some conversation surgery is necessary here for now...
            conversation = copy.deepcopy(conversation) # avoid mutating the original
            messages = conversation["messages"]
            assert messages[1]["role"] == "user", "System message must be followed by a user message"
            messages[1]["content"] = messages[0]["content"] + "\n\n" + messages[1]["content"]
            messages = messages[1:]
        else:
            messages = conversation["messages"]
        assert len(messages) >= 1, f"Conversation has less than 1 message: {messages}"

        # fetch all the special tokens we need
        bos = self.get_bos_token_id()
        user_start, user_end = self.encode_special("<|user_start|>"), self.encode_special("<|user_end|>")
        assistant_start, assistant_end = self.encode_special("<|assistant_start|>"), self.encode_special("<|assistant_end|>")
        python_start, python_end = self.encode_special("<|python_start|>"), self.encode_special("<|python_end|>")
        output_start, output_end = self.encode_special("<|output_start|>"), self.encode_special("<|output_end|>")

        # now we can tokenize the conversation
        add_tokens(bos, 0)
        for i, message in enumerate(messages):

            # some sanity checking here around assumptions, to prevent footguns
            must_be_from = "user" if i % 2 == 0 else "assistant"
            assert message["role"] == must_be_from, f"Message {i} is from {message['role']} but should be from {must_be_from}"

            # content can be either a simple string or a list of parts (e.g. containing tool calls)
            content = message["content"]

            if message["role"] == "user":
                assert isinstance(content, str), "User messages are simply expected to be strings"
                value_ids = self.encode(content)
                add_tokens(user_start, 0)
                add_tokens(value_ids, 0)
                add_tokens(user_end, 0)
            elif message["role"] == "assistant":
                add_tokens(assistant_start, 0)
                if isinstance(content, str):
                    # simple string => simply add the tokens
                    value_ids = self.encode(content)
                    add_tokens(value_ids, 1)
                elif isinstance(content, list):
                    for part in content:
                        value_ids = self.encode(part["text"])
                        if part["type"] == "text":
                            # string part => simply add the tokens
                            add_tokens(value_ids, 1)
                        elif part["type"] == "python":
                            # python tool call => add the tokens inside <|python_start|> and <|python_end|>
                            add_tokens(python_start, 1)
                            add_tokens(value_ids, 1)
                            add_tokens(python_end, 1)
                        elif part["type"] == "python_output":
                            # python output => add the tokens inside <|output_start|> and <|output_end|>
                            # none of these tokens are supervised because the tokens come from Python at test time
                            add_tokens(output_start, 0)
                            add_tokens(value_ids, 0)
                            add_tokens(output_end, 0)
                        else:
                            raise ValueError(f"Unknown part type: {part['type']}")
                else:
                    raise ValueError(f"Unknown content type: {type(content)}")
                add_tokens(assistant_end, 1)

        # truncate to max_tokens tokens MAX (helps prevent OOMs)
        ids = ids[:max_tokens]
        mask = mask[:max_tokens]
        if return_positions:
            # computed after truncation, which is equivalent: positions only depend on the prefix
            align_at, align_after = self._conversation_boundaries()
            positions = compute_conversation_position_ids(ids, message_stride, align_at, align_after)
            return ids, mask, positions
        return ids, mask

    def visualize_tokenization(self, ids, mask, with_token_id=False):
        """Small helper function useful in debugging: visualize the tokenization of render_conversation"""
        RED = '\033[91m'
        GREEN = '\033[92m'
        RESET = '\033[0m'
        GRAY = '\033[90m'
        tokens = []
        for i, (token_id, mask_val) in enumerate(zip(ids, mask)):
            token_str = self.decode([token_id])
            color = GREEN if mask_val == 1 else RED
            tokens.append(f"{color}{token_str}{RESET}")
            if with_token_id:
                tokens.append(f"{GRAY}({token_id}){RESET}")
        return '|'.join(tokens)

    def render_for_completion(self, conversation):
        """
        Used during Reinforcement Learning. In that setting, we want to
        render the conversation priming the Assistant for a completion.
        Unlike the Chat SFT case, we don't need to return the mask.
        """
        # We have some surgery to do: we need to pop the last message (of the Assistant)
        conversation = copy.deepcopy(conversation) # avoid mutating the original
        messages = conversation["messages"]
        assert messages[-1]["role"] == "assistant", "Last message must be from the Assistant"
        messages.pop() # remove the last message (of the Assistant) inplace

        # Now tokenize the conversation
        ids, mask = self.render_conversation(conversation)

        # Finally, to prime the Assistant for a completion, append the Assistant start token
        assistant_start = self.encode_special("<|assistant_start|>")
        ids.append(assistant_start)
        return ids

# -----------------------------------------------------------------------------
# nanochat-specific convenience functions

def get_tokenizer():
    from nanochat.common import get_base_dir
    base_dir = get_base_dir()
    tokenizer_dir = os.path.join(base_dir, "tokenizer")
    return RustBPETokenizer.from_directory(tokenizer_dir)

def get_token_bytes(device="cpu"):
    import torch
    from nanochat.common import get_base_dir
    base_dir = get_base_dir()
    tokenizer_dir = os.path.join(base_dir, "tokenizer")
    token_bytes_path = os.path.join(tokenizer_dir, "token_bytes.pt")
    assert os.path.exists(token_bytes_path), f"Token bytes not found at {token_bytes_path}? It gets written by tok_train.py"
    with open(token_bytes_path, "rb") as f:
        token_bytes = torch.load(f, map_location=device)
    return token_bytes
